# Generated by Django 6.0.7 on 2026-08-03 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_doctorinvite_otp_code_emailverificationtoken_otp_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jazzcash_number", models.CharField(blank=True, max_length=20)),
                (
                    "jazzcash_account_title",
                    models.CharField(blank=True, max_length=150),
                ),
                ("easypaisa_number", models.CharField(blank=True, max_length=20)),
                (
                    "easypaisa_account_title",
                    models.CharField(blank=True, max_length=150),
                ),
                ("bank_name", models.CharField(blank=True, max_length=150)),
                ("bank_account_title", models.CharField(blank=True, max_length=150)),
                ("bank_account_number", models.CharField(blank=True, max_length=50)),
                ("bank_iban", models.CharField(blank=True, max_length=50)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="area",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="city",
            field=models.CharField(
                blank=True,
                choices=[
                    ("karachi", "Karachi"),
                    ("lahore", "Lahore"),
                    ("islamabad", "Islamabad"),
                    ("rawalpindi", "Rawalpindi"),
                    ("faisalabad", "Faisalabad"),
                    ("multan", "Multan"),
                    ("peshawar", "Peshawar"),
                    ("quetta", "Quetta"),
                    ("hyderabad", "Hyderabad"),
                    ("sialkot", "Sialkot"),
                    ("gujranwala", "Gujranwala"),
                    ("sargodha", "Sargodha"),
                    ("bahawalpur", "Bahawalpur"),
                    ("sukkur", "Sukkur"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_patient_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                help_text="Admin's free-text note, e.g. a JazzCash transaction ID.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="trial_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
